version: "3"

services:
#  bank-service:
#    image: "newbank/bank-service"
#    environment:
#      - POSTGRES_HOST=postgres-bank:5432
#    ports:
#      - 3000:3000
#
#  cashback-service:
#    image: "newbank/cashback-service"
#    environment:
#      - POSTGRES_HOST=postgres-cashback:5432
#    ports:
#      - 3001:3001


  external-bank-mock-service:
    image: "newbank/external-bank-mock-service"
    ports:
      - 5000:8080


  # the postgres DB to be connected to the backend (watch out: no volume specified, everything can be lost)
  postgres-bank:
    image: postgres:15.2
    container_name: database-bank
    environment:
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_USER=postgresuser
      - POSTGRES_DB=database-bank
    ports:
      - "4000:5432"

  postgres-cashback:
    image: postgres:15.2
    container_name: database-cashback
    environment:
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_USER=postgresuser
      - POSTGRES_DB=database-cashback
    ports:
      - "4001:5432"