version: "3"

services:
#  bank-service:
#    image: "newbank/bank-service"
#    environment:
#      - POSTGRES_HOST=postgres-bank:5432
#    ports:
#      - 3000:3000
#
#  cashback-service:
#    image: "newbank/cashback-service"
#    environment:
#      - POSTGRES_HOST=postgres-cashback:5432
#    ports:
#      - 3001:3001

  transaction-service:
    image: "newbank/transaction-service"
    environment:
      - POSTGRES_HOST=postgres-transaction:5432
      - POSTGRESQL_DATABASE=database-transaction
    ports:
      - "3001:8080"
    depends_on:
      - postgres-transaction

  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  external-bank-mock-service:
    image: "newbank/external-bank-mock-service"
    restart: always
    ports:
      - "5000:8080"

  external-mid-interpreter-mock-service:
    image: "newbank/external-mid-interpreter-mock-service"
    restart: always
    ports:
      - "5001:8080"

  external-mastercard-mock-service:
    image: "newbank/external-mastercard-mock-service"
    restart: always
    ports:
      - "5002:8080"

  external-decathlon-mock-service:
    image: "newbank/external-decathlon-mock-service"
    restart: always
    ports:
      - "5003:8080"

  external-carrefour-mock-service:
    image: "newbank/external-carrefour-mock-service"
    restart: always
    ports:
      - "5004:8080"

  # the postgres DB to be connected to the backend (watch out: no volume specified, everything can be lost)
  postgres-bank:
    image: postgres:15.2
    container_name: database-bank
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_USER=postgresuser
      - POSTGRES_DB=database-bank
    ports:
      - "4000:5432"


  postgres-account:
    image: postgres:15.2
    container_name: database-account
    environment:
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_USER=postgresuser
      - POSTGRES_DB=database-account
    ports:
      - "4003:5432"

  postgres-cashback:
    image: 'bitnami/postgresql:latest'
    container_name: database-cashback
    restart: always
    environment:
      - POSTGRESQL_PASSWORD=postgrespass
      - POSTGRESQL_USER=postgresuser
      - POSTGRESQL_DATABASE=database-cashback
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
    ports:
      - "4001:5432"
    volumes:
      - ./cashback-directory-master:/var/lib/postgresql/data

  postgres-cashback-slave:
    image: 'bitnami/postgresql:latest'
    container_name: database-cashback-slave
    restart: always
    depends_on:
      - postgres-cashback
    environment:
      - POSTGRESQL_USER=postgresuser
      - POSTGRESQL_PASSWORD=postgrespass
      - POSTGRESQL_MASTER_HOST=postgres-cashback
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    ports:
      - "4002:5432"
    volumes:
      - ./cashback-directory-slave:/var/lib/postgresql/data

  postgres-transaction:
    image: 'bitnami/postgresql:latest'
    container_name: database-transaction
    restart: always
    environment:
      - POSTGRESQL_PASSWORD=postgrespass
      - POSTGRESQL_USER=postgresuser
      - POSTGRESQL_DATABASE=database-transaction
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
    ports:
      - "4005:5432"
    volumes:
      - ./transaction-directory-master:/var/lib/postgresql/data

  postgres-transaction-slave:
    image: 'bitnami/postgresql:latest'
    container_name: database-transaction-slave
    restart: always
    depends_on:
      - postgres-transaction
    environment:
      - POSTGRESQL_USER=postgresuser
      - POSTGRESQL_PASSWORD=postgrespass
      - POSTGRESQL_MASTER_HOST=postgres-transaction
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    ports:
      - "4006:5432"
    volumes:
      - ./transaction-directory-slave:/var/lib/postgresql/data

  # the postgres DB to be connected to the backend (watch out: no volume specified, everything can be lost)
  postgres-affiliated-store:
    image: postgres:15.2
    container_name: database-affiliated-store
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_USER=postgresuser
      - POSTGRES_DB=database-affiliated-store
    ports:
      - "4004:5432"